blog/urls.py
from django.urls import path

from . import views 

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('search/', views.Search.as_view(), name='search'),
    path('blog/', views.Blog.as_view(), name='blog'),
    path('blog/<int:pk>/',views.BlogArchiveByCategoryPK.as_view(), name='blog_archive_by_category_pk'),
    path('blog/<str:slug>/', views.BlogSingle.as_view(), name='blog_single'),
    path('blog/<int:pk>/<str:slug>/', views.BlogSingle.as_view(), name='blog_single'),
    path('videocast/', views.Videocast.as_view(), name='videocast'),
    path('videocast/<int:pk>/', views.VideocastArchiveByCategoryPK.as_view(), name='videocast_archive_by_category_pk'),
    path('videocast/<str:slug>/', views.VideocastSingle.as_view(), name='videocast_single'),
    path('videocast/<int:pk>/<str:slug>/', views.VideocastSingle.as_view(), name='videocast_single'),
    path('podcast/', views.Podcast.as_view(), name='podcast'),
    path('podcast/<int:pk>/', views.PodArchiveByCategoryPK.as_view(), name='podcast_archive_by_category_pk'),
    path('podcast/<str:slug>/', views.PodSingle.as_view(), name='podcast_single'),
    path('podcast/<int:pk>/<str:slug>/', views.PodSingle.as_view(), name='podcast_single'),
]

blog_web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/archive.html
{% extends 'base.html' %}

{% block content %}
    <!-- Section - archive -->
    <section id="archive">
        <header class="major">
            <h2>Archive</h2>
        </header>
        <div class="posts">
            {% for archive in archives %}
                <article>
                    <a href="{{ request.path }}{{ archive.slug }}" class="image" title="{{ archive.title }}">
                        <img src="{{ archive.thumbnail.url }}" alt="{{ archive.title }}"/>
                    </a>
                    <h3>{{ archive.title }}</h3>
                    <p>{{ archive.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{{ request.path }}{{ archive.slug }}" class="button" title="{{ archive.title }}">More</a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - archive -->
{% endblock %}

templates/base.html
{% load static %}
{% get_media_prefix as MEDIA_URL %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ config.SITE_TITLE }}</title>
    <meta name="description" content="{{ config.SITE_DESCRIPTION }}">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static '/assets/css/main.css' %}"/>
    <link rel="icon" href="{{ MEDIA_URL }}{{ config.SITE_FAVICON }}" type="image/png" sizes="16x16">
</head>
<body class="is-preload">

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <div id="main">
        <div class="inner">

            <!-- Header -->
            <header id="header">
                <a href="{% url 'blog:index' %}" class="logo"><strong>{{ config.SITE_TITLE }}</strong></a>
                <ul class="icons">
                    {% if config.SOCIAL_NETWORKS_TWITTER_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_TWITTER_URL }}" class="icon brands fa-twitter"
                               title="Twitter"><span class="label">Twitter</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_FACEBOOK_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_FACEBOOK_URL }}" class="icon brands fa-facebook-f"
                               title="Facebook"><span class="label">Facebook</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_SNAPCHAT_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_SNAPCHAT_URL }}" class="icon brands fa-snapchat-ghost"
                               title="Snapchat"><span class="label">Snapchat</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_INSTAGRAM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_INSTAGRAM_URL }}" class="icon brands fa-instagram"
                               title="Instagram"><span class="label">Instagram</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_MEDIUM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_MEDIUM_URL }}" class="icon brands fa-medium-m"
                               title="Medium"><span class="label">Medium</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_TELEGRAM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_TELEGRAM_URL }}" class="icon brands fa-telegram"
                               title="Telegram"><span class="label">Telegram</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_GITHUB_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_GITHUB_URL }}" class="icon brands fa-github"
                               title="Github"><span class="label">Github</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_GITLAB_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_GITLAB_URL }}" class="icon brands fa-gitlab"
                               title="Gitlab"><span class="label">Gitlab</span></a></li>
                    {% endif %}
                </ul>
            </header>
            <!-- /Header -->

            {% block content %}
            {% endblock %}

        </div>
    </div>

    <!-- Sidebar -->
    <div id="sidebar">
        <div class="inner">

            <!-- Search -->
            <section id="search" class="alt">
                <form method="GET" action="/search/">
                    <input type="text" name="query" id="query" placeholder="Search"/>
                </form>
            </section>
            <!-- /Search -->

            <!-- Menu -->
            <nav id="menu">
                <header class="major">
                    <h2>Menu</h2>
                </header>
                <ul>
                    <li><a href="{% url 'blog:index' %}">Homepage</a></li>
                    <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                    <li>
                        <span class="opener">Blog Categories</span>
                        <ul>
                            {% for blogs_category in blogs_categories %}
                                <li><a href="{% url 'blog:blog_archive_by_category_pk' blogs_category.pk %}">{{ blogs_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'blog:videocast' %}">Videocast</a></li>
                    <li>
                        <span class="opener">Videocast Categories</span>
                        <ul>
                            {% for videocasts_category in videocasts_categories %}
                                <li><a href="{% url 'blog:videocast_archive_by_category_pk' videocasts_category.pk %}">{{ videocasts_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'blog:podcast' %}">Podcast</a></li>
                    <li>
                        <span class="opener">Podcast Categories</span>
                        <ul>
                            {% for podcast_category in podcast_categories %}
                                <li><a href="{% url 'blog:podcast_archive_by_category_pk' podcast_category.pk %}">{{ podcast_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /Menu -->

            <!-- Section - podcast -->
            <section id="podcast">
                <header class="major">
                    <h2>Trending</h2>
                </header>
                <div class="mini-posts">
                    {% for podcast in podcasts %}
                        <article>
                            <a href="{% url 'blog:podcast_single' podcast.slug %}" class="image">
                                <img src="{{ podcast.thumbnail.url }}" alt="{{ podcast.title }}"/>
                            </a>
                            <p>{{ podcast.blog | safe |truncatewords_html:15 }}</p>
                            <a href="{% url 'blog:podcast_single' podcast.slug %}" class="button">More</a>
                        </article>
                    {% endfor %}
                </div>
            </section>
            <!-- /Section - podcast -->

            {% if config.GET_IN_TOUCH_ACTIVE == 'yes' %}
                <!-- get_in_touch -->
                <section id="get_in_touch">
                    <header class="major">
                        <h2>Get in touch</h2>
                    </header>
                    <p>{{ config.GET_IN_TOUCH_INFO | safe }}</p>
                    <ul class="contact">
                        <li class="icon solid fa-envelope">
                            <a href="mailto:{{ config.GET_IN_TOUCH_EMAIL_ADDRESS }}">{{ config.GET_IN_TOUCH_EMAIL_ADDRESS }}</a>
                        </li>
                        <li class="icon solid fa-phone">
                            {{ config.GET_IN_TOUCH_PHONE }}
                        </li>
                        <li class="icon solid fa-home">
                            {{ config.GET_IN_TOUCH_ADDRESS | safe }}
                        </li>
                        <li style="font-size: 1.75rem;">
                            <a href="{{ config.SOCIAL_NETWORKS_GITHUB_URL }}" class="icon brands fa-github"></a>
                            <a href="{{ config.SOCIAL_NETWORKS_GITHUB_URL }}" class="icon brands fa-facebook"></a>
                            <a href="{{ config.SOCIAL_NETWORKS_GITHUB_URL }}" class="icon brands fa-instagram"></a>
                        </li>
                        
                    </ul>
                </section>
                <!-- /get_in_touch -->
            {% endif %}

            <!-- Footer -->
            <footer id="footer">
                <p class="copyright">
                    &copy; MyBlog. All rights reserved. Design: <a href="https://github.com/raja53a">@Code</a>. CMS: <a
                        href="https://github.com/raja53a" title="">MyBlog</a></p>
            </footer>
            <!-- /Footer -->

        </div>
    </div>

</div>

<!-- Scripts -->
<script src="{% static '/assets/js/jquery.min.js' %}"></script>
<script src="{% static '/assets/js/browser.min.js' %}"></script>
<script src="{% static '/assets/js/breakpoints.min.js' %}"></script>
<script src="{% static '/assets/js/util.js' %}"></script>
<script src="{% static '/assets/js/main.js' %}"></script>
<!-- /Scripts -->

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% for last_post in last_blog %}
        <!-- Banner -->
        <section id="banner">
            <div class="content">
                <header>
                    <h1>{{ last_post.title }}</h1>
                </header>
                <p>{{ last_post.content | safe | truncatewords_html:30 }}</p>
                <ul class="actions">
                    <li>
                        <a href="{% url 'blog:blog_single' last_post.slug %}" class="button big" title="{{ last_post.title }}">
                            Learn More
                        </a>
                    </li>
                </ul>
            </div>
            <span class="image object">
                <img src="{{ last_post.thumbnail.url }}" alt="{{ last_post.title }}"/>
            </span>
        </section>
        <!-- /Banner -->
    {% endfor %}

    <!-- Section - Skills -->
    <section id="skills">
        <header class="major">
            <h2>Blogs</h2>
        </header>
        <div class="features">
            {% for skill in skills %}
                <article>
                    <span class="icon solid {{ skill.icon }}"></span>
                    <div class="content">
                        <h3>{{ skill.title }}</h3>
                        <p>{{ skill.description }}</p>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section -->

    <!-- Section - blog -->
    <section id="blog">
        <header class="major">
            <h2>Trending</h2>
        </header>
        <div class="posts">
            {% for blog_post in blogs %}
                <article>
                    <a href="{% url 'blog:blog_single' blog_post.slug %}" class="image" title="{{ blog_post.title }}">
                        <img src="{{ blog_post.thumbnail.url }}" alt="{{ blog_post.title }}"/>
                    </a>
                    <h3>{{ blog_post.title }}</h3>
                    <p>{{ blog_post.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'blog:blog_single' blog_post.slug %}" class="button" title="{{ blog_post.title }}">More</a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - blog -->

    <!-- Section - Videocast -->
    <section id="videocast">
        <header class="major">
            <h2>The latest Videocasts</h2>
        </header>
        <div class="posts">
            {% for videocast in videocasts %}
                <article>
                    <a href="{% url 'blog:videocast_single' videocast.slug %}" class="image" title="{{ videocast.title }}">
                        <img src="{{ videocast.thumbnail.url }}" alt="{{ videocast.title }}"/>
                    </a>
                    <h3>{{ videocast.title }}</h3>
                    <p>{{ videocast.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'blog:videocast_single' videocast.slug %}" class="button" title="{{ videocast.title }}">More</a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - Videocast -->
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block content %}
    <section id="archive">
        <header class="major">
            <h2>Search Result</h2>
        </header>
        <div>
            {% for blog in blogs %}
                <article>
                    <a href="{% url 'blog:blog_single' blog.slug %}" title="{{ blog.title }}">
                        <h3>{{ blog.title }}</h3>
                    </a>                    
                    <p>{{ blog.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}
            
            {% for videocast in videocasts %}
                <article>
                    <a href="{% url 'blog:videocast_single' videocast.slug %}" title="{{ videocast.title }}">
                        <h3>{{ videocast.title }}</h3>
                    </a>                    
                    <p>{{ videocast.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}

            {% for podcast in podcasts %}
                <article>
                    <a href="{% url 'blog:podcast_single' podcast.slug %}" title="{{ podcast.title }}">
                        <h3>{{ podcast.title }}</h3>
                    </a>                    
                    <p>{{ podcast.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}                        
        </div>
    </section>
{% endblock %}

templates/single.html
{% extends 'base.html' %}

{% block content %}
    {% for single in single_content %}
    <!-- Content -->
    <section>
        <header class="main">
            <h1>{{ single.title }}</h1>
        </header>

        <span class="image main">
            <img src="{{ single.thumbnail.url }}" alt="{{ single.title }}"/>
        </span>

        {{ single.content | safe }}

        {% if single.video %}
            <a href="{{ single.video }}" class="button primary fit icon solid fa-video">Show Video</a>
        {% endif %}

        {% if single.audio %}
            <a href="{{ single.audio.url }}" class="button primary fit icon solid fa-download">Download Audio</a>
        {% endif %}

    </section>
    <!-- /Content -->
    {% endfor %}
{% endblock %}